name: Build, Test & Publish

on:
  push:
    branches: [release/v*.*.*, bugfix/*, feature/*, features/*, master, dev]
  pull_request:
    branches: [release/v*.*.*, bugfix/*, feature/*, features/*, master, dev]
  
jobs:
  build:
    name: Building repo
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      id-token: write
      pull-requests: write
    container: ghcr.io/kiracore/docker/base-image:v0.13.11
    steps:
      
      - name: Add safe.directory
        id: add-safe-dir
        run: |
          git config --global --add safe.directory /github/workspace
          git config --global --add safe.directory $PWD

      - name: Checkout repository
        id: checkout-repo
        uses: actions/checkout@v3

      - name: Extract branch name on push
        id: extract-branch-name-push
        if: github.event_name == 'push'
        shell: bash
        run: |
          echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          echo "DESTINATION_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      
      - name: Extract branch name on pull request
        id: extract-branch-name-pull
        if: github.event_name == 'pull_request'
        env:
          REF_BRANCH: ${{ github.event.pull_request.head.ref }}
          BASE_REF_BRANCH: ${{ github.base_ref }}
        shell: bash
        run: |
          echo "SOURCE_BRANCH=$(echo ${{ env.REF_BRANCH }})" >> $GITHUB_ENV
          echo "DESTINATION_BRANCH=$(echo ${{ env.BASE_REF_BRANCH }})" >> $GITHUB_ENV
      - name: Print job results
        run: |
          echo "Add safe.directory...             ${{ steps.add-safe-dir.outcome }}"
          echo "Checkout repository...            ${{ steps.world.outcome }}"
          echo "Extract branch name on push...    ${{ steps.extract-branch-push.outcome }}"
          echo "Extract branch name on pull...    ${{ steps.extract-branch-pull.outcome }}"
